### ISSUE TITLE
Abbruch beim Start mit Kodi 17.0 auf Fire TV

### ISSUE THREAD

**Issue by ghost** [prof-membrane/plugin.video.3satmediathek#1]
Betriebssystem: Android ARM 64-bit API level 21 (API level 21) Linux ARM 64-bit version 3.10.61+
Kodi Version: 17.0
Add-on Version: 1.0.0
Bibliothek: lib3sat - im Log keine Version gefunden. 
Bibliothek: libMediathek3 - im Log keine Version gefunden. 

3sat-Mediathek lässt sich auf dem Fire TV auf Kodi 17.0 64 bit nicht starten, [Log](http://pastebin.com/p44jqxWD) ist bei Pastebin.

Aufruf: Videos -> Video-Addons -> 3sat Mediathek. 

Meldung: "3sat Mediathek Fehler Für mehr Informationen, Logdatei einsehen". 

Trifft auch auf ARD-Mediathek 4.9.3 zu (da habe ich kein Log gezogen, kann ich aber nachholen, wenn es ein anderes Problem ist). ZDF-Mediathek 4.0.0 scheint allerdings zu funktionieren. Weitere nicht getestet.

**Comment by prof-membrane** [comment]
Veraltete Version installiert.

**Comment by ghost** [comment]
Mit dem [Commit auf die addons.xml von heute Morgen](https://github.com/prof-membrane/repository.membrane/commit/147712b8323a6a035ca209450e48ff98f3ae1538#diff-c2a588160a1d0d66e5f588a70d1aa1d2) wurden dann auch aus dem Repository nicht veraltete Versionen aktualisiert (3sat Mediathek jetzt auf 1.2.0 statt 1.0.0). Scheint jetzt zu laufen. Danke schön.

**Comment by prof-membrane** [comment]
Im offiziellen Repo war auch vorher die neue Version...

**Comment by ghost** [comment]
Hm, dann habe ich offenbar nicht das offizielle Repository installiert. Keine Ahnung, was ich installiert hatte, ich hätte gedacht, es war http://github.com/prof-membrane/repository.membrane/raw/master/addons.xml und das wäre das, was zu installieren war. Entschuldige, ich störe nicht weiter.

**Comment by prof-membrane** [comment]
Das offizielle Repo hat jeder installiert, der Kodi von der offiziellen Webseite hat/LibreElec nutzt. Dort sind auch alle Add-ons vorhanden. Hier werden nur kleinere Verbesserungen zum testen hochgeladen.

Bis gestern war mein Repo noch auf Jarvis, jetzt hat es Krypton Add-ons.
